cp -v bootstrap.min.css .
cp -v font-awesome.css .
cp -v datepicker3.css .
cp -v toastr.min.css .
cp -v animate.css .
cp -v style.css .
cp -v clockpicker.css .
cp -v jquery.steps.css .
cp -v custom.css .
cp -v jquery.bootstrap-touchspin.min.css .
cp -v datatables.min.css .
cp -v highcharts.css .
cp -v angular-material.min.css .
cp -v keycloak2.js .
cp -v jquery-3.1.1.min.js .
cp -v angular.js .
cp -v angular-animate.min.js .
cp -v angular-aria.min.js .
cp -v angular-messages.min.js .
cp -v angular-material.min.js .
cp -v deploy.sh .
cp -v bootstrap.min.js .
cp -v bootstrap-datepicker.js .
cp -v clockpicker.js .
cp -v moment.min.js .
cp -v jquery.metisMenu.js .
cp -v datatables.min.js .
cp -v inspinia.js .
cp -v pace.min.js .
cp -v angular-ui-utils.min.js .
cp -v angular-resource.js .
cp -v angular-route.js .
cp -v angular-cookies.js .
cp -v angular-js-xlsx.js .
cp -v xlsx.core.min.js .
cp -v sweetalert.min.js .
cp -v toastr.min.js .
cp -v jquery.steps.min.js .
cp -v icheck.min.js .
cp -v jquery.bootstrap-touchspin.min.js .
cp -v highcharts.js .
cp -v exporting.js .
cp -v Chart.min.js .
cp -v Sucursales.js .
